apiVersion: v1
items:
- apiVersion: resource.k8s.io/v1
  kind: DeviceClass
  metadata:
    annotations:
      meta.helm.sh/release-name: nvidia-dra-driver-gpu
      meta.helm.sh/release-namespace: nvidia-dra-driver-gpu
    creationTimestamp: "2026-04-05T02:14:48Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    name: compute-domain-daemon.nvidia.com
    resourceVersion: "520090633"
    uid: cc91e934-55d4-4e3e-be93-987ce5e769f6
  spec:
    selectors:
    - cel:
        expression: device.driver == 'compute-domain.nvidia.com' && device.attributes['compute-domain.nvidia.com'].type
          == 'daemon'
- apiVersion: resource.k8s.io/v1
  kind: DeviceClass
  metadata:
    annotations:
      meta.helm.sh/release-name: nvidia-dra-driver-gpu
      meta.helm.sh/release-namespace: nvidia-dra-driver-gpu
    creationTimestamp: "2026-04-05T02:14:48Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    name: compute-domain-default-channel.nvidia.com
    resourceVersion: "520090634"
    uid: cc826719-d61f-47fe-876c-c59d41088ce4
  spec:
    selectors:
    - cel:
        expression: device.driver == 'compute-domain.nvidia.com' && device.attributes['compute-domain.nvidia.com'].type
          == 'channel' && device.attributes['compute-domain.nvidia.com'].id == 0
- apiVersion: resource.k8s.io/v1
  kind: DeviceClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"resource.k8s.io/v1","kind":"DeviceClass","metadata":{"annotations":{},"name":"dranet"},"spec":{"selectors":[{"cel":{"expression":"device.driver == \"dra.net\""}}]}}
    creationTimestamp: "2026-04-05T16:06:30Z"
    generation: 1
    name: dranet
    resourceVersion: "524016949"
    uid: cb323f76-384a-4f02-9662-93e86b584800
  spec:
    selectors:
    - cel:
        expression: device.driver == "dra.net"
- apiVersion: resource.k8s.io/v1
  kind: DeviceClass
  metadata:
    annotations:
      meta.helm.sh/release-name: nvidia-dra-driver-gpu
      meta.helm.sh/release-namespace: nvidia-dra-driver-gpu
    creationTimestamp: "2026-04-05T02:14:48Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    name: gpu.nvidia.com
    resourceVersion: "520090636"
    uid: 514aebce-4af7-4d2c-89b1-0265386a50f2
  spec:
    selectors:
    - cel:
        expression: device.driver == 'gpu.nvidia.com' && device.attributes['gpu.nvidia.com'].type
          == 'gpu'
- apiVersion: resource.k8s.io/v1
  kind: DeviceClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"resource.k8s.io/v1","kind":"DeviceClass","metadata":{"annotations":{},"name":"host-device-kernel"},"spec":{"config":[{"opaque":{"driver":"sriovnetwork.k8snetworkplumbingwg.io","parameters":{"apiVersion":"sriovnetwork.k8snetworkplumbingwg.io/v1alpha1","kind":"VfConfig","netAttachDefName":"sriov-net"}}}],"selectors":[{"cel":{"expression":"device.driver == 'sriovnetwork.k8snetworkplumbingwg.io' \u0026\u0026 device.attributes['sriovnetwork.k8snetworkplumbingwg.io'].interfaceType == 'Regular' \u0026\u0026 device.attributes['sriovnetwork.k8snetworkplumbingwg.io'].linkType == 'ethernet' \u0026\u0026 device.attributes['sriovnetwork.k8snetworkplumbingwg.io'].rdmaCapable == true"}}]}}
    creationTimestamp: "2026-04-30T14:12:54Z"
    generation: 2
    name: host-device-kernel
    resourceVersion: "674215667"
    uid: d5d1d336-e809-4573-bb16-c32b0e73c5ab
  spec:
    config:
    - opaque:
        driver: sriovnetwork.k8snetworkplumbingwg.io
        parameters:
          apiVersion: sriovnetwork.k8snetworkplumbingwg.io/v1alpha1
          kind: VfConfig
          netAttachDefName: sriov-net
    selectors:
    - cel:
        expression: device.driver == 'sriovnetwork.k8snetworkplumbingwg.io' && device.attributes['sriovnetwork.k8snetworkplumbingwg.io'].interfaceType
          == 'Regular' && device.attributes['sriovnetwork.k8snetworkplumbingwg.io'].rdmaCapable
          == true
- apiVersion: resource.k8s.io/v1
  kind: DeviceClass
  metadata:
    annotations:
      meta.helm.sh/release-name: nvidia-dra-driver-gpu
      meta.helm.sh/release-namespace: nvidia-dra-driver-gpu
    creationTimestamp: "2026-04-05T02:14:48Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    name: mig.nvidia.com
    resourceVersion: "520090632"
    uid: cb6b1493-5a27-4864-a408-cca14bc5144e
  spec:
    selectors:
    - cel:
        expression: device.driver == 'gpu.nvidia.com' && device.attributes['gpu.nvidia.com'].type
          == 'mig'
- apiVersion: resource.k8s.io/v1
  kind: DeviceClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"resource.k8s.io/v1","kind":"DeviceClass","metadata":{"annotations":{},"name":"network.nvidia.com"},"spec":{"selectors":[{"cel":{"expression":"device.driver == \"nvidia.com/roce\""}}]}}
    creationTimestamp: "2026-04-05T00:04:19Z"
    generation: 1
    name: network.nvidia.com
    resourceVersion: "519469931"
    uid: 795231ca-c6a8-4a1c-a717-b108dd2960b6
  spec:
    selectors:
    - cel:
        expression: device.driver == "nvidia.com/roce"
- apiVersion: resource.k8s.io/v1
  kind: DeviceClass
  metadata:
    annotations:
      meta.helm.sh/release-name: nvidia-dra-driver-gpu
      meta.helm.sh/release-namespace: nvidia-dra-driver-gpu
    creationTimestamp: "2026-04-05T02:14:48Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    name: vfio.gpu.nvidia.com
    resourceVersion: "520090637"
    uid: 972c4ecd-cc6e-423d-9c0b-27aee9e75e79
  spec:
    selectors:
    - cel:
        expression: device.driver == 'gpu.nvidia.com' && device.attributes['gpu.nvidia.com'].type
          == 'vfio'
kind: List
metadata:
  resourceVersion: ""
