apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: {{ .Values.deviceClass.name }}
  labels:
    {{- include "composite-dra.labels" . | nindent 4 }}
spec:
  selectors:
    - cel:
        expression: {{ .Values.deviceClass.selector | quote }}
  {{- if .Values.deviceClass.extendedResourceName }}
  extendedResourceName: {{ .Values.deviceClass.extendedResourceName | quote }}
  {{- end }}
