apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: {{ .Values.deviceClass.name }}
  labels:
    {{- include "composite-dra.labels" . | nindent 4 }}
spec:
  selectors:
    - cel:
        expression: {{ .Values.deviceClass.selector | quote }}
  {{- if ne (include "composite-dra.webhookNeeded" .) "true" }}
  extendedResourceName: {{ .Values.deviceClass.extendedResourceName | default (printf "%s/%s" .Values.driver.name (index .Values.compositions 0).name) | quote }}
  {{- else if .Values.deviceClass.extendedResourceName }}
  extendedResourceName: {{ .Values.deviceClass.extendedResourceName | quote }}
  {{- end }}
